import { useCart } from "@/context/CartContext";
import PickupTimePicker from "@/components/PickupTimePicker";
import { supabase } from "@/lib/supabaseClient";
import { useMemo, useState } from "react";
import QRCode from "react-qr-code";

function Price({ cents }: { cents: number }) {
  return <span>₱{(Number(cents || 0) / 100).toFixed(2)}</span>;
}

export default function CheckoutPage() {
  const { items, clear } = useCart();
  const [pickup, setPickup] = useState(() =>
    new Date(Date.now() + 60 * 60 * 1000).toISOString().slice(0, 16)
  );
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [loading, setLoading] = useState(false);
  const [placed, setPlaced] = useState<{
    id: string;
    tracking_code: string;
  } | null>(null);

  const cartEmpty = items.length === 0;

  const subtotal = useMemo(
    () => items.reduce((sum, it) => sum + Number(it.unit_price_cents || 0), 0),
    [items]
  );

  function validatePickup(ts: string) {
    const dt = new Date(ts);
    return dt.getTime() > Date.now() + 5 * 60 * 1000; // at least 5 minutes from now
  }

  function phoneLooksOk(v: string) {
    if (!v) return true;
    const digits = v.replace(/\D/g, "");
    return digits.length >= 10 && digits.length <= 13;
  }

  async function placeOrder() {
    if (cartEmpty) return alert("Your cart is empty.");
    if (!validatePickup(pickup))
      return alert("Pickup time must be at least 5 minutes from now.");
    if (!(name.trim() || phone.trim()))
      return alert("Please provide at least your name or phone number.");
    if (!phoneLooksOk(phone))
      return alert("Enter a valid phone number (10–13 digits).");

    setLoading(true);
    try {
      // 1️⃣ Create main order — tracking_code auto-generated by DB
      const { data: order, error: orderErr } = await supabase
        .from("orders")
        .insert({
          pickup_time: new Date(pickup).toISOString(),
          guest_name: name.trim() || null,
          guest_phone: phone.trim() || null,
          status: "pending",
        })
        .select("id, tracking_code")
        .single();

      if (orderErr || !order)
        throw orderErr || new Error("Failed to create order.");

      // 2️⃣ Insert each item + its ingredients
      for (let idx = 0; idx < items.length; idx++) {
        const it = items[idx];
        const { data: oi, error: oiErr } = await supabase
          .from("order_items")
          .insert({
            order_id: order.id,
            drink_id: it.drink_id ?? null,
            item_name: it.item_name,
            size_ml: it.size_ml ?? null,
            unit_price_cents: it.unit_price_cents,
            line_total_cents: it.unit_price_cents,
            position: idx,
          })
          .select("id")
          .single();

        if (oiErr || !oi) throw oiErr || new Error("Failed to add order item.");

        // Ingredients per item
        const lineRows =
          (it.lines || []).map((l) => ({
            order_item_id: oi.id,
            ingredient_id: l.ingredient_id,
            amount: Number(l.amount),
            unit: l.unit,
            is_extra: !!(l as any).is_extra,
          })) || [];

        if (lineRows.length > 0) {
          const { error: liErr } = await supabase
            .from("order_item_ingredients")
            .insert(lineRows);
          if (liErr) throw liErr;
        }
      }

      clear();
      setPlaced({ id: order.id, tracking_code: order.tracking_code });
    } catch (err: any) {
      alert(err.message || "Something went wrong placing your order.");
    } finally {
      setLoading(false);
    }
  }

  if (placed) {
    const trackUrl = `${window.location.origin}/track/${placed.tracking_code}`;
    return (
      <div className="flex flex-col items-center justify-center py-12 space-y-6">
        <div className="rounded-2xl border bg-white p-6 shadow-sm w-full max-w-md text-center">
          <h1 className="text-2xl font-bold text-[#D26E3D] mb-2">
            Order Placed 🎉
          </h1>
          <p className="text-gray-700 mb-4">
            Thank you! We’ll start preparing your drink near your pickup time.
          </p>
          <p className="text-sm text-gray-600 mb-4">
            Scan or share this QR to track your order in real time:
          </p>

          <div className="flex justify-center mb-4">
            <QRCode value={trackUrl} size={180} />
          </div>

          <div className="text-sm font-medium break-all text-gray-700">
            {trackUrl}
          </div>

          <button
            onClick={() => navigator.clipboard.writeText(trackUrl)}
            className="mt-4 w-full rounded-lg border px-3 py-2 text-sm hover:bg-gray-50"
          >
            Copy Tracking Link
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      <h1 className="text-xl font-extrabold tracking-tight">Checkout</h1>

      <div className="grid gap-4 md:grid-cols-3">
        {/* Left column: pickup & contact */}
        <div className="md:col-span-2 space-y-4">
          <div className="rounded-2xl border bg-white p-4">
            <div className="font-semibold">Pickup Time</div>
            <div className="mt-2">
              <PickupTimePicker value={pickup} onChange={setPickup} />
            </div>
            <p className="mt-1 text-xs text-gray-500">
              Choose a time at least a few minutes from now.
            </p>
          </div>

          <div className="rounded-2xl border bg-white p-4">
            <div className="font-semibold">Contact</div>
            <p className="mt-1 text-xs text-gray-500">
              Please add your name or phone so we can reach you if needed.
            </p>
            <div className="mt-3 grid gap-2 md:grid-cols-2">
              <input
                className="rounded-lg border px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-[#D26E3D]/30"
                placeholder="Your Name"
                value={name}
                onChange={(e) => setName(e.target.value)}
              />
              <input
                className="rounded-lg border px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-[#D26E3D]/30"
                placeholder="Phone Number"
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
              />
            </div>
          </div>
        </div>

        {/* Right column: summary */}
        <aside className="md:col-span-1">
          <div className="rounded-2xl border bg-white p-4">
            <div className="mb-2 flex items-center justify-between">
              <div className="font-semibold">Order Summary</div>
              <div className="rounded bg-gray-50 px-2 py-0.5 text-xs text-gray-600">
                {items.length} item{items.length > 1 ? "s" : ""}
              </div>
            </div>

            <ul className="divide-y divide-gray-100 text-sm">
              {items.map((it, i) => (
                <li key={i} className="py-2">
                  <div className="flex items-start justify-between gap-2">
                    <div className="min-w-0">
                      <div className="truncate font-medium">
                        {it.base_drink_name
                          ? `Custom — ${it.base_drink_name}`
                          : it.item_name}
                      </div>
                      {typeof it.base_price_cents === "number" &&
                        typeof it.addons_price_cents === "number" && (
                          <div className="mt-0.5 text-[11px] text-gray-500">
                            Base <Price cents={it.base_price_cents} /> · Add-ons{" "}
                            <Price cents={it.addons_price_cents} />
                          </div>
                        )}
                    </div>
                    <div className="shrink-0">
                      <Price cents={it.unit_price_cents} />
                    </div>
                  </div>
                </li>
              ))}
            </ul>

            <div className="mt-3 flex items-center justify-between text-base">
              <div className="font-medium">Subtotal</div>
              <div className="font-semibold">
                <Price cents={subtotal} />
              </div>
            </div>

            <button
              disabled={loading || cartEmpty}
              onClick={placeOrder}
              className="mt-4 w-full rounded-lg bg-[#D26E3D] px-4 py-2 text-sm font-semibold text-white transition hover:opacity-90 disabled:opacity-50"
            >
              {loading ? "Placing…" : "Place Order"}
            </button>
            <p className="mt-2 text-[11px] text-gray-500 text-center">
              You’ll receive a tracking QR and link after checkout.
            </p>
          </div>
        </aside>
      </div>
    </div>
  );
}
